name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # every hour (00 minuts)
  workflow_dispatch: # 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.3
        with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_repo: LibreCAD/LibreCAD
          upstream_sync_branch: master
